<script type="text/javascript" src="/admin/library/javascript/jquery-1.7.1.min.js"></script>
<script type="text/javascript" src="/admin/library/javascript/jquery.backgroundPosition.js"></script>
<script type="text/javascript" src="/admin/library/javascript/jquery.placeholder.min.js"></script>
<script type="text/javascript" src="/admin/library/javascript/jquery.ui.1.8.17.js"></script>
<script type="text/javascript" src="/admin/library/javascript/jquery.ui.select.js"></script>
<script type="text/javascript" src="/admin/library/javascript/jquery.ui.spinner.js"></script>
<script type="text/javascript" src="/admin/library/javascript/superfish.js"></script>
<script type="text/javascript" src="/admin/library/javascript/supersubs.js"></script>
<script type="text/javascript" src="/admin/library/javascript/jquery.datatables.js"></script>
<script type="text/javascript" src="/admin/library/javascript/fullcalendar.min.js"></script>
<script type="text/javascript" src="/admin/library/javascript/jquery.smartwizard-2.0.min.js"></script>
<script type="text/javascript" src="/admin/library/javascript/pirobox.extended.min.js"></script>
<script type="text/javascript" src="/admin/library/javascript/jquery.tipsy.js"></script>
<script type="text/javascript" src="/admin/library/javascript/jquery.elastic.source.js"></script>
<script type="text/javascript" src="/admin/library/javascript/jquery.jBreadCrumb.1.1.js"></script>
<script type="text/javascript" src="/admin/library/javascript/jquery.customInput.js"></script>
<script type="text/javascript" src="/admin/library/javascript/jquery.validate.min.js"></script>
<script type="text/javascript" src="/admin/library/javascript/jquery.metadata.js"></script>
<script type="text/javascript" src="/admin/library/javascript/jquery.filestyle.mini.js"></script>
<script type="text/javascript" src="/admin/library/javascript/jquery.filter.input.js"></script>
<script type="text/javascript" src="/admin/library/javascript/jquery.flot.js"></script>
<script type="text/javascript" src="/admin/library/javascript/jquery.flot.pie.min.js"></script>
<script type="text/javascript" src="/admin/library/javascript/jquery.flot.resize.min.js"></script>
<script type="text/javascript" src="/admin/library/javascript/jquery.graphtable-0.2.js"></script>
<script type="text/javascript" src="/admin/library/javascript/jquery.wysiwyg.js"></script>
<script type="text/javascript" src="/admin/library/javascript/controls/wysiwyg.image.js"></script>
<script type="text/javascript" src="/admin/library/javascript/controls/wysiwyg.link.js"></script>
<script type="text/javascript" src="/admin/library/javascript/controls/wysiwyg.table.js"></script>
<script type="text/javascript" src="/admin/library/javascript/plugins/wysiwyg.rmFormat.js"></script>
<script type="text/javascript" src="/admin/library/javascript/costum.js"></script>
<script type="text/javascript" src="/library/javascript/jquery.colorbox-min.js"></script>